/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mutter_ffaudioplayer_FFAudioPlayer */

#ifndef _Included_com_mutter_ffaudioplayer_FFAudioPlayer
#define _Included_com_mutter_ffaudioplayer_FFAudioPlayer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mutter_ffaudioplayer_FFAudioPlayer_OUTPUT_MODE_OPEN_SL_ES
#define com_mutter_ffaudioplayer_FFAudioPlayer_OUTPUT_MODE_OPEN_SL_ES 479L
#undef com_mutter_ffaudioplayer_FFAudioPlayer_OUTPUT_MODE_AUDIO_TRACK_SINGLE_BUFFER
#define com_mutter_ffaudioplayer_FFAudioPlayer_OUTPUT_MODE_AUDIO_TRACK_SINGLE_BUFFER 289L
#undef com_mutter_ffaudioplayer_FFAudioPlayer_OUTPUT_MODE_AUDIO_TRACK_BYTE_ARRAY
#define com_mutter_ffaudioplayer_FFAudioPlayer_OUTPUT_MODE_AUDIO_TRACK_BYTE_ARRAY 286L
#undef com_mutter_ffaudioplayer_FFAudioPlayer_PLAYER_EVENT_ON_AUDIO_DATA_AVAILABLE
#define com_mutter_ffaudioplayer_FFAudioPlayer_PLAYER_EVENT_ON_AUDIO_DATA_AVAILABLE 0L
#undef com_mutter_ffaudioplayer_FFAudioPlayer_PLAYER_EVENT_INIT
#define com_mutter_ffaudioplayer_FFAudioPlayer_PLAYER_EVENT_INIT 1L
#undef com_mutter_ffaudioplayer_FFAudioPlayer_PLAYER_EVENT_START
#define com_mutter_ffaudioplayer_FFAudioPlayer_PLAYER_EVENT_START 2L
#undef com_mutter_ffaudioplayer_FFAudioPlayer_PLAYER_EVENT_PAUSE
#define com_mutter_ffaudioplayer_FFAudioPlayer_PLAYER_EVENT_PAUSE 3L
#undef com_mutter_ffaudioplayer_FFAudioPlayer_PLAYER_EVENT_STOP
#define com_mutter_ffaudioplayer_FFAudioPlayer_PLAYER_EVENT_STOP 4L
#undef com_mutter_ffaudioplayer_FFAudioPlayer_PLAYER_EVENT_DESTROY
#define com_mutter_ffaudioplayer_FFAudioPlayer_PLAYER_EVENT_DESTROY 5L
/*
 * Class:     com_mutter_ffaudioplayer_FFAudioPlayer
 * Method:    nativeInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_mutter_ffaudioplayer_FFAudioPlayer_nativeInit
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_mutter_ffaudioplayer_FFAudioPlayer
 * Method:    nativeSetDataSource
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mutter_ffaudioplayer_FFAudioPlayer_nativeSetDataSource
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mutter_ffaudioplayer_FFAudioPlayer
 * Method:    nativeSetOutputSink
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_mutter_ffaudioplayer_FFAudioPlayer_nativeSetOutputSink
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_mutter_ffaudioplayer_FFAudioPlayer
 * Method:    nativeSetOutputMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mutter_ffaudioplayer_FFAudioPlayer_nativeSetOutputMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mutter_ffaudioplayer_FFAudioPlayer
 * Method:    nativeSetHandler
 * Signature: (Landroid/os/Handler;)V
 */
JNIEXPORT void JNICALL Java_com_mutter_ffaudioplayer_FFAudioPlayer_nativeSetHandler
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_mutter_ffaudioplayer_FFAudioPlayer
 * Method:    nativeStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mutter_ffaudioplayer_FFAudioPlayer_nativeStart
  (JNIEnv *, jclass);

/*
 * Class:     com_mutter_ffaudioplayer_FFAudioPlayer
 * Method:    nativePause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mutter_ffaudioplayer_FFAudioPlayer_nativePause
  (JNIEnv *, jclass);

/*
 * Class:     com_mutter_ffaudioplayer_FFAudioPlayer
 * Method:    nativeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mutter_ffaudioplayer_FFAudioPlayer_nativeStop
  (JNIEnv *, jclass);

/*
 * Class:     com_mutter_ffaudioplayer_FFAudioPlayer
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mutter_ffaudioplayer_FFAudioPlayer_nativeDestroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
