//
// Created by mutter on 8/18/16.
//

#ifndef NATIVECOOKBOOK_FFPLAYER_H
#define NATIVECOOKBOOK_FFPLAYER_H

#include <jni.h>

typedef enum {
    FF_PLAYER_MSG_START = 0,
    FF_PLAYER_MSG_ON_PICTURE_AVAILABLE,
    FF_PLAYER_MSG_ON_SOUND_AVAILABLE,
    FF_PLAYER_MSG_STOP,
    FF_PLAYER_MSG_PROGRESS_UPDATE
} FFPlayerMSGType;

typedef enum {
    FF_PLAYER_STATE_PLAYING,
    FF_PLAYER_STATE_PAUSED,
    FF_PLAYER_STATE_STOPPED
} FFPlayerState;


#endif //NATIVECOOKBOOK_FFPLAYER_H
